### ISSUE TITLE
smplayer?

### ISSUE THREAD

**Issue by kupiqu** [mrlotfi/mpv-libunity#2]
Nice work!

Guess not easy (or even possible) but wondering whether this could work on players that run mpv in the background, such as smplayer.

Asking because mpv does not support MPRIS...

**Comment by mrlotfi** [comment]
Hey @kupiqu. Did you try https://github.com/hoyon/mpv-mpris/ ? It adds mpris to mpv and works like a charm.

**Comment by mrlotfi** [comment]
And if you insist on using smplayer, just edit the libunity.c and replace `mpv.desktop` with `smplayer.desktop`

**Comment by kupiqu** [comment]
> Hey @kupiqu. Did you try https://github.com/hoyon/mpv-mpris/ ? It adds mpris to mpv and works like a charm.

Great! didn't know about it
